// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfs_UZrpw6IiJKJ7iSLaDZ7dx3Oy4ZzSk',
    appId: '1:747992756939:web:6acb5f9d0d4d104c79a14e',
    messagingSenderId: '747992756939',
    projectId: 'backend-practice-c1f40',
    authDomain: 'backend-practice-c1f40.firebaseapp.com',
    storageBucket: 'backend-practice-c1f40.firebasestorage.app',
    measurementId: 'G-DKSRESDX3L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF39fmk5I17sJz7sTOuAR5JmpojEqgpM8',
    appId: '1:747992756939:android:50b42ae69047e67779a14e',
    messagingSenderId: '747992756939',
    projectId: 'backend-practice-c1f40',
    storageBucket: 'backend-practice-c1f40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb7yJqlAu5unGBBkoxvz8vpaxQUvs5cEU',
    appId: '1:747992756939:ios:60c864a97fa4354979a14e',
    messagingSenderId: '747992756939',
    projectId: 'backend-practice-c1f40',
    storageBucket: 'backend-practice-c1f40.firebasestorage.app',
    iosBundleId: 'com.example.codeStructure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb7yJqlAu5unGBBkoxvz8vpaxQUvs5cEU',
    appId: '1:747992756939:ios:60c864a97fa4354979a14e',
    messagingSenderId: '747992756939',
    projectId: 'backend-practice-c1f40',
    storageBucket: 'backend-practice-c1f40.firebasestorage.app',
    iosBundleId: 'com.example.codeStructure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfs_UZrpw6IiJKJ7iSLaDZ7dx3Oy4ZzSk',
    appId: '1:747992756939:web:b35ae23aa644d0ec79a14e',
    messagingSenderId: '747992756939',
    projectId: 'backend-practice-c1f40',
    authDomain: 'backend-practice-c1f40.firebaseapp.com',
    storageBucket: 'backend-practice-c1f40.firebasestorage.app',
    measurementId: 'G-RSW53SS55W',
  );
}
